name: grocery_home
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^0.0.13
  email_auth:
  firebase_storage: ^5.2.0
  firebase_core: ^0.5.3
  firebase_analytics: 
  firebase_auth: ^0.18.0
  shared_preferences: 
  cloud_firestore: 
  modal_progress_hud: ^0.1.3
  font_awesome_flutter: ^9.1.0
  image_picker: ^0.6.7+14
  flutter_spinkit:
  firebase_messaging: 
  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/beverages/Beverages1.jpg
    - assets/beverages/Beverages2.jpeg
    - assets/biscuit/Biscuit1.jpg
    - assets/biscuit/Biscuit2.jpg
    - assets/biscuit/Biscuit3.jpg
    - assets/biscuit/Biscuit4.jpg
    - assets/biscuit/Biscuit5.jpg
    - assets/category/Category1.png
    - assets/category/Category2.jpg
    - assets/category/Category3.jpg
    - assets/category/Category4.jpg
    - assets/category/Category5.jpg
    - assets/fruits/Fruit1.jpg
    - assets/fruits/Fruit2.jpg
    - assets/fruits/Fruit3.jpg
    - assets/fruits/Fruit4.jpg
    - assets/fruits/Fruit5.jpg
    - assets/fruits/Fruit6.jpg
    - assets/fruits/Fruit7.jpg
    - assets/fruits/Fruit8.jpg
    - assets/nuts/Nuts1.png
    - assets/nuts/Nuts2.png
    - assets/vegetables/Vegetables1.jpg
    - assets/vegetables/Vegetables2.jpg
    - assets/vegetables/Vegetables3.jpg
    - assets/vegetables/Vegetables4.jpeg
    - assets/vegetables/Vegetables5.jpg
    - assets/offers/Offer1.jpg
    - assets/offers/Offer2.jpg
    - assets/offers/Offer3.jpg
    - assets/offers/Offer4.jpg
    - assets/offers/Offer5.jpg
    - assets/icon.jpeg
    - assets/uploadPhoto.jpg

